### ISSUE TITLE
Kp, Ki an Kd granular setting toggle

### ISSUE THREAD

**Issue by therealsputnik** [andremiller/Sous_Viduino#1]
When selecting the _SetPoint_ value, you can use the "**Select**" button to toggle between single digits increment/decrement or smaller units 1/10th of a degree for a more precise temp.

When changing the settings for the **Kp**, **Ki** and **Kd** this doesn't work.  The values will only increase by single numbers and not smaller increments.  

Example:  Auto-Tune determines **Kp** to be 2.66 so it sets this value.  There is currently no way to change it to 2.00 if that is the value you prefer.  Only the "**2**" can be modified, not the ".**66**".

Pressing "**select**" should allow the toggle to the numbers after the decimal which can then be incremented/decremented as needed.  Pressing select again would return to numbers in front of the decimal point so that exact values can always be achieved.

**Comment by andremiller** [comment]
Should be fixed in 94878056ac5d89250f1e3bb9ee89b0cf1969463d

Select toggles between the increments and it also displays the increment on the LCD. The value is also rounded to two decimal places, in case AutoTune sets it a value with three decimal places.
