### ISSUE TITLE
Pre-Heat

### ISSUE THREAD

**Issue by therealsputnik** [andremiller/Sous_Viduino#5]
Pre-heat function should be added to speed up the process of arriving at the setpoint.

For example, if setpoint is 60C and water temp is 30C at power on, run the heating element (ie, relay ON) constantly until DOUBLE the value of the proportional band (Kp) so that the PID can take over as the system stabilizes around the setpoint.

If you make a static value, say 10C, then if the Kp = 15 you will have a problem in that the PID will want to start turning off the relay accordingly BEFORE the relay is allowed to go off.  Double the Kp value should give it time to "hand over" to the PID smoothly.

**Comment by andremiller** [comment]
Check if this pre-heat feature will be sufficient? It's very basic. You define an offset (default 3C), and it will keep the heater on until it gets within that offset before switching to PID.
This is based on the suggestion made here:  https://forums.adafruit.com/viewtopic.php?f=22&t=47039#p236473

**Comment by therealsputnik** [comment]
3 Degree's seems a bit closer to SP than I would have chosen, but only testing will confirm whether it's adequate.  It probably will be just fine since I've noticed initial overshoot to be 2-3 degree's while testing with some test values.

**Comment by andremiller** [comment]
It's configurable (in the code), so you can adjust it based on your setup.

**Comment by therealsputnik** [comment]
Great!  Testing thus far reveals that 3 degree's is a pretty sensible value.  Worked well in my latest testing.  I consider this solved.
